### ISSUE TITLE
Что за странный комментарий?

### ISSUE THREAD

**Issue by coursar** [OneSeven17/HW2lesson#3]
https://github.com/OneSeven17/HW2lesson/blob/8d56b16ff87824a299ae12a175b68226cc327e45/hw2func.py#L8

**Comment by OneSeven17** [comment]
я имел ввиду то, что данный способ округления будет неверен, в случае, если результатом деления периметра на ширину рулона будет целое число. Если периметр составит, к примеру, 1060см, то поделив на ширину рулона 106см, получим 10, но согласно формуле необходимо прибавить еще 0.5 и при округлении получим strip_quantity = 11.
